---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "minimal-webapp-service"
  namespace: "default"
  labels:
    app: "minimal-webapp"
spec:
  ports:
  - protocol: "TCP"
    port: 5000
  selector:
    app: "minimal-webapp"
  type: "LoadBalancer"
  loadBalancerIP: ""
